// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE45ulvF4QLtDfaHOd-5sAX4i8klYeR_U',
    appId: '1:578826630769:web:3556efd1887ac2e96a8dd0',
    messagingSenderId: '578826630769',
    projectId: 'authdb-545bf',
    authDomain: 'authdb-545bf.firebaseapp.com',
    storageBucket: 'authdb-545bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo-tn3XMDwt5Hrm_8pUiezis81AeADYz4',
    appId: '1:578826630769:android:9250a15e26aa59186a8dd0',
    messagingSenderId: '578826630769',
    projectId: 'authdb-545bf',
    storageBucket: 'authdb-545bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQds6nNurhWJHZhCYTPqavTqiFamVg_gw',
    appId: '1:578826630769:ios:f323791d839762d06a8dd0',
    messagingSenderId: '578826630769',
    projectId: 'authdb-545bf',
    storageBucket: 'authdb-545bf.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQds6nNurhWJHZhCYTPqavTqiFamVg_gw',
    appId: '1:578826630769:ios:f323791d839762d06a8dd0',
    messagingSenderId: '578826630769',
    projectId: 'authdb-545bf',
    storageBucket: 'authdb-545bf.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );
}
